GET http://localhost:9999/api/posts

###

POST http://localhost:9999/api/posts
Content-Type: application/json

{
  "id": 4,
  "content": "Last Post nnnn"
}

###

DELETE http://localhost:9999/api/posts/2


###

GET http://localhost:9999/api/posts/2